### ISSUE TITLE
3D printers for beginners

### ISSUE THREAD

**Issue by nazroll** [5050frames/core-frame-system#2]
I am a beginner in 3d printing. It will be helpful if i can have some information on which 3d printers that i can buy.

* Which 3D printers should I buy as a beginner?
* What kind of materials should I buy for my first sidewall?
* Where can I send my designs in Europe?

**Comment by 5050frames** [comment]
I hope to have a section on the Developer Portal that gives some walkthroughs for this, but until then here's some text I wrote up:

> So you’ve got your design and you’re ready to print, but you don’t know where to start? Here’s a few lessons we’ve learned from printing parts.
> 
> There are lots of great printers on the market, but we recommend the Creality CR-10 for its ease of use and solid performance. The print bed is 300x300x400, which is more than enough room for printing a Large frame wall diagonally. You can usually find them for less than $400 on Amazon. You don’t need the latest and greatest, the CR-10 is a workhorse and offers more than enough for what we need.
> 
> Fusion 360 is the software of choice for most hobbyists, and Cura is great for preparing your STL file for your printer. 
> 
> We’re tested a bunch of different filaments, but the best performing material for the price we’ve found is PLA Max. Not only is it cheap (around $20-$25 for 1000g), but PLA Max is compostable! We recommend the CC3D brand based on available colors and consistency with prints. When printing PLA Max, we’ve found that 215F is the ideal temperature to avoid banding. This temperature can be changed in Cura or whatever slicing software you use.
> 
> Frame walls should be printed at 100% infill to be skateable, but for fitting tests we typically print at 20%. They’ll still work just fine for skating to test rockers and grooves, but won’t last very long and may crack unexpectedly.
