### ISSUE TITLE
Technical drawings

### ISSUE THREAD

**Issue by michaeltrilford** [5050frames/core-frame-system#9]
I'm struggling to measure/find the specific measurements of the hardware.

E.g. What is the diameter of the bolts (Is it 8.234mm?)

I was wondering if there is a way to find this information today, if not, technical drawings (Agnostic to a drawing program) would be good to add to this repo.

Context about my situation:

- I'm using Fusion360
- I'm converting Mesh to the preferred modelling method, as I can't edit the current models

**Comment by 5050frames** [comment]
I believe the axles in the CDK are the production axles. So the .step file is what we sent to the factory for making the toolings.

**Comment by michaeltrilford** [comment]
Yeh, I was keen to start with a wall and remove the logo.

I actually couldn’t do that, I can take a look a again as I’ve learnt the program.

Unsure if I could access history / sketch and remove the core system logo

**Comment by HeXiBLiTz** [comment]
Hey Michael,

You can access all of the sketches through the Sample wall files. to pull them to your own project simple open the sketch you want (so it's editable) select it all and Ctrl+c then create a new sketch in your own project and Ctrl+V to paste. (Sorry I don't know the key binds for copy and paste on Mac but hopefully, you get the idea :)
![image](https://user-images.githubusercontent.com/47713975/164629351-251cf55d-0e2d-4c50-9401-84732f34e186.png)

**Comment by michaeltrilford** [comment]
I found the logo really hard to select and extrude it back into shape.

Maybe I will be able to do it, after the learning the programs. I will take a look and see if I wasted my time building my own wall from scratch. Haha.

**Comment by michaeltrilford** [comment]
> Hey Michael,
> 
> You can access all of the sketches through the Sample wall files. to pull them to your own project simply open the sketch you want (so it's editable) select it all and Ctrl+c then create a new sketch in your own project and Ctrl+V to paste. (Sorry I don't know the key binds for copy and paste on Mac but hopefully, you get the idea :) ![image](https://user-images.githubusercontent.com/47713975/164629351-251cf55d-0e2d-4c50-9401-84732f34e186.png)
> 
> The logo is probably an SVG file extruded out of the wall also

Your one looks like a working file. Interesting

**Comment by HeXiBLiTz** [comment]
the sketch for the logo in on the centre plane (essentially between the walls in the middle. you'd have to manually select each segment by clicking the sketch so hiding the walls etc whilst you do that will help make it easier to select which parts you want to extrude. 
That file is the sample wall file in this repo, there is also a core .Step file.
and on the note of of building your own from scratch that's a good thing, use the CDK as references and reverse engineer the files/build your own it'll help you learn the software and have a understand of how it is all made :)

**Comment by michaeltrilford** [comment]
> the sketch for the logo is on the centre plane (essentially between the walls in the middle. you'd have to manually select each segment by clicking the sketch so hiding the walls etc whilst you do that will help make it easier to select which parts you want to extrude.
> That file is the sample wall file in this repo, there is also a core .Step file.
> and on the note of building your own from scratch that's a good thing, use the CDK as references and reverse engineer the files/build your own it'll help you learn the software and have a understanding of how it is all made :)

Thank you mate! I agree, it did help. I didn’t do any tutorials either. Quite intuitive an application!

Here’s the progression! Based around Arlo’s NFT project:
![9ABC9F63-A9AD-4324-9983-80F180D2A7BC](https://user-images.githubusercontent.com/2483515/164641984-c7043075-0ace-434b-990c-a7d12cc86e9a.jpeg)
![3A914A14-36B5-4B04-A783-C2D27F8E9DFF](https://user-images.githubusercontent.com/2483515/164642010-c529c4af-9d1f-44b8-9fc9-9a762e8f2567.jpeg)
![03480406-1B43-43D1-AB6B-A409C5DCB6F7](https://user-images.githubusercontent.com/2483515/164642024-00d4a9f4-a6bf-45cd-ae2a-c7ee4b5ce4f5.jpeg)
![71E42D82-E8B3-4C4D-9B8A-968D8515F348](https://user-images.githubusercontent.com/2483515/164642042-e52278cc-9e39-4230-bc25-c37ec8c9a5b9.jpeg)


![162C784B-C8EF-44E3-8906-5823A8A73B9B](https://user-images.githubusercontent.com/2483515/164641920-8aa5e4c0-1f46-47e2-8a0a-2770b00680aa.jpeg)
